// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0sGwcKNKIXGj9gXCUShDAK-Rb0xel1fI',
    appId: '1:136049611:web:a0c1eb5d17975d76937c4e',
    messagingSenderId: '136049611',
    projectId: 'todo-40aa3',
    authDomain: 'todo-40aa3.firebaseapp.com',
    storageBucket: 'todo-40aa3.appspot.com',
    measurementId: 'G-3CKXY02QMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsn32GlLaaIJGOjs_wzi24PiCnN2BzFdw',
    appId: '1:136049611:android:a4b3e1ae95c5c5de937c4e',
    messagingSenderId: '136049611',
    projectId: 'todo-40aa3',
    storageBucket: 'todo-40aa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjXHrMe-obK7zHhnHXlLQFU5ksYDjdDF4',
    appId: '1:136049611:ios:37a8ea1b0bad097a937c4e',
    messagingSenderId: '136049611',
    projectId: 'todo-40aa3',
    storageBucket: 'todo-40aa3.appspot.com',
    iosClientId: '136049611-lj4t533cr3ug9gouj2m2gf78sgferrog.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjXHrMe-obK7zHhnHXlLQFU5ksYDjdDF4',
    appId: '1:136049611:ios:37a8ea1b0bad097a937c4e',
    messagingSenderId: '136049611',
    projectId: 'todo-40aa3',
    storageBucket: 'todo-40aa3.appspot.com',
    iosClientId: '136049611-lj4t533cr3ug9gouj2m2gf78sgferrog.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRiverpod',
  );
}
