// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM1am_YgCUDYwFKEYLdhCYUDtetVuybEE',
    appId: '1:754164381545:web:c56ea1b6e00d7056ebaff8',
    messagingSenderId: '754164381545',
    projectId: 'todorivepod',
    authDomain: 'todorivepod.firebaseapp.com',
    storageBucket: 'todorivepod.appspot.com',
    measurementId: 'G-W8P1QBK85P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgzpwtVSKUcj-5216oU25yf8BEJZo7LU',
    appId: '1:754164381545:android:aad3e03d68435816ebaff8',
    messagingSenderId: '754164381545',
    projectId: 'todorivepod',
    storageBucket: 'todorivepod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZIiMiz6LQD8Zj6lpFG_JxG5h0y_L6fyc',
    appId: '1:754164381545:ios:599b3840033c9e37ebaff8',
    messagingSenderId: '754164381545',
    projectId: 'todorivepod',
    storageBucket: 'todorivepod.appspot.com',
    iosClientId: '754164381545-3s5d1shjdliafnbhc15borcefi1io616.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZIiMiz6LQD8Zj6lpFG_JxG5h0y_L6fyc',
    appId: '1:754164381545:ios:599b3840033c9e37ebaff8',
    messagingSenderId: '754164381545',
    projectId: 'todorivepod',
    storageBucket: 'todorivepod.appspot.com',
    iosClientId: '754164381545-3s5d1shjdliafnbhc15borcefi1io616.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRiverpod',
  );
}
